# Generated by Django 4.2.16 on 2024-11-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede Visualizar el catalogo'), ('add_vehiculomodel', 'Puede Agregar Nuevos Vehiculos')]},
        ),
    ]
